#!/usr/bin/env bash
# Regenerates the live-demo preview block in README.md from git remote origin.
# Note: GitHub strips <iframe> from README — we use a clickable preview image instead.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
README="$ROOT/README.md"
REMOTE="${1:-$(git -C "$ROOT" config --get remote.origin.url 2>/dev/null || true)}"

if [[ -z "$REMOTE" ]]; then
  echo "No git remote. Usage: $0 [git-remote-url]" >&2
  exit 1
fi

# https://github.com/owner/repo(.git) -> owner, repo
if [[ "$REMOTE" =~ github\.com[:/]([^/]+)/([^/.]+) ]]; then
  OWNER="${BASH_REMATCH[1]}"
  REPO="${BASH_REMATCH[2]%.git}"
else
  echo "Could not parse GitHub owner/repo from: $REMOTE" >&2
  exit 1
fi

PAGES_URL="https://${OWNER}.github.io/${REPO}/"

EMBED="$(cat <<EOF
<!-- embed:start — generated by scripts/update-readme-embed.sh; do not edit manually -->
<p align="center">
  <a href="${PAGES_URL}">
    <img
      src="preview.png"
      alt="CME P00 Interactive Playground — click to open live demo"
      width="960"
      style="max-width:100%;border:1px solid #30363d;border-radius:12px;"
    />
  </a>
</p>

<p align="center"><strong><a href="${PAGES_URL}">▶ Open interactive demo</a></strong></p>
<!-- embed:end -->
EOF
)"

python3 - "$README" "$EMBED" <<'PY'
import re, sys
path, embed = sys.argv[1], sys.argv[2]
text = open(path, encoding="utf-8").read()
pattern = r"<!-- embed:start.*?<!-- embed:end -->"
if not re.search(pattern, text, flags=re.S):
    print("Missing <!-- embed:start --> … <!-- embed:end --> markers in README.md", file=sys.stderr)
    sys.exit(1)
text = re.sub(pattern, embed.strip(), text, count=1, flags=re.S)
open(path, "w", encoding="utf-8").write(text)
PY

echo "Updated README preview → ${PAGES_URL}"
echo "GitHub does not render <iframe> in README; using preview.png + link instead."
